### ISSUE TITLE
Compare with TRPC?

### ISSUE THREAD

**Issue by sergeylukin** [jlaamanen/flayer#85]
Hey,

I find this package similar to [TRPC](https://trpc.io/), could you elaborate on how both compare?

Thanks!

**Comment by jlaamanen** [comment]
Certainly, thanks for your interest!

I started working on this package way before I even had heard about tRPC, but the basic idea is indeed similar - to improve developer experience by allowing direct server-side function calls from the client-side.

My main approach with Flayer has been to improve developer experience as much as possible. I thought it was interesting to find out how seamless could full-stack development possibly be, even if it meant some unorthodox decisions or performance losses.

By no means am I a tRPC expert, but I'll do my best to describe some differences. Feel free to correct me if I'm wrong in any of these claims or assumptions.

----

### Flayer is experimental

Let's start with probably the most obvious point: Flayer is still at an early experimental stage and is not suitable for production use. tRPC is production-ready, and I'm also using it in some work projects to some extent. 

### Flayer generates a stand-alone NPM package for clients

Because of this, the client and backend sources aren't directly connected via imports, as in tRPC. For Flayer, this makes it possible to even publish the server API to outside clients via NPM. However, in tRPC this tight source code coupling makes it possible to easily refactor functions and jump to their declarations. I believe implementing such IDE features is a lot trickier (if not even impossible) in Flayer.

In Flayer, you also need to regenerate the package everytime your server-side code changes. It doesn't seem to be a huge deal though, because during development you can just tell Flayer to regenerate the package whenever the server restarts. In my small-scale tests the package generation has been quite fast (some hundreds of milliseconds), but any larger-scale applications are yet to be tested.

This also means that Flayer is highly dependant on Node.js, at least for now. In the future, it may be possible to generate packages for other runtimes as well.

### Flayer has JSDoc support

When you document a function with JSDoc, it also gets included in the client-side package, alongside the type definitions. It's quite useful to be able to have a quick glance on a function's (and its parameters') documentation without having to jump to the server-side code.

### Flayer can "serialize" almost anything, even functions

IIRC, in tRPC the default serialization is just a simple `JSON.stringify` & `JSON.parse`. It's easy to hook up with [superjson](https://github.com/blitz-js/superjson) for more extensive serialization though.

In Flayer you can pass arguments (or return variables) of almost any type out-of-the-box: even functions. This makes it easy to start listening to server-side events just by passing callback functions as arguments. Note that the contents of these functions aren't actually serialized per se, so they aren't actually passed on to the other side.

### Flayer has even less overhead & is more seamless

After setting Flayer up, adding a new function is as simple as - well, writing a new function. You can define an entire source file as a "module", which makes any exported function in the file a function that you can invoke from the clients. You don't need to define inputs or procedure methods (query vs. mutation) for the function, because all functions are handled the same way in Flayer. If you're interested, please check out the [example](https://github.com/jlaamanen/flayer/tree/master/examples/01-crud-with-auth).

The only difference between the client-side and the server-side function signatures is that the client-side signature is always asynchronous, i.e. it always returns a `Promise`. Other than that, the function should look identical to the function defined in the server-side.

### Flayer has built-in sessions

In Flayer it is easy to get or update session data anywhere in your server-side code, without having to pass context data (e.g. logged-in user data) as arguments. This takes advantage of the [`AsyncLocalStorage`](https://nodejs.org/api/async_context.html#class-asynclocalstorage) API in Node.js. Every client connection creates a new asynchronous context, and to get or update the current session anywhere in the code, you can simply call Flayer's `getSession` or `setSession`.

### Flayer uses WebSockets for all data transfer (at least for now)

This enables asynchronous two-way communication between the ends via callback functions. On the downside, Flayer cannot take advantage of browsers' built-in HTTP request caching. I've been thinking of making HTTP requests an option for more synchronous functions though, but not in the near future.

----

That's pretty much all that I could think off the top of my head, hope it didn't get too heavy to read!

I still want to say that tRPC is an awesome library, but I'll keep working on Flayer on my free-time to see if it's worth developing further. I'd still love to code some larger-scale hobby project with it to really find out if it's any good in other than small-scale examples.
